### ISSUE TITLE
Transfer gem/repo maintenance?

### ISSUE THREAD

**Issue by markrebec** [markrebec/zuul#1]
Hi Wes.  I recently built an authorization solution as part of a suite of apps my company is rolling out.  I'm working on extracting the core access control functionality into a gem and making it a bit more generic and configurable, and would love to release it to the community.

I've been a huge ghostbusters nut since childhood, and so of course zuul was the first thing I searched rubygems.org for :)

It looks like there hasn't been much work done on the gem in a few years - which may very well be because it's stable and you're using it in production?  However, if that's not the case, if you've actually stopped using the gem or if you consider it abandoned, I would absolutely love to take it over and run with it.

The solution I've built provides a set authorization functionality for ActiveRecord, as well as a DSL to implement access control for ActionController, so it's not a Rails specific solution but works great in a Rails app.  

I'm still working on extracting it and filling out tests, and it was built for `actionpack 3.0.0` and `activerecord 3.0.0` (in a rails 3.2.x app), but it should work with the 2.x branches as well (once tests are filled in I'll be testing against many versions of ruby, actionpack and activerecord).

I'd be happy to show you what I've got so far so you can verify it's a quality solution, and would of course bump the version when introducing my new stuff into the gem (if you're up for a handover, that is).

Thanks!

**Comment by wesgibbs** [comment]
Hey Mark. Sorry about the delay; I've been on vacation.

I'm happy to transfer ownership of the repo over to you. I'll do it now. Let me know if there are any issues and thanks for reaching out!

![Screen Shot 2013-03-12 at 8 48 05 AM](https://f.cloud.github.com/assets/9358/249372/4662d112-8b2c-11e2-8705-65b1837a972e.png)

**Comment by markrebec** [comment]
Hi Wes. Thanks so much!  Aside from loving the name, I was sort of dreading throwing yet another access control gem out there for folks to sort through, so I really like the idea of bringing my stuff into Zuul.  I haven't gotten a notification yet, but I believe that's because repo transfers usually require manual approval by github.  Once it goes through, I'll push up the repo and you can take a look at what I've got if you'd like.  I'd absolutely welcome any input, feedback or contributions you might have!  Thanks again.

**Comment by wesgibbs** [comment]
Sounds great!

**Comment by markrebec** [comment]
Looks like the transfer completed over the weekend!  I've started merging in my new stuff, namespacing it all to zuul, adding documentation, etc.  

Thanks again, Wes, and maybe once I wrap up documentation, a few more specs and a couple other things you'd be willing to chat about the rubygems.org gem?

**Comment by wesgibbs** [comment]
Yeah, happy to.
